package common.enums;

public enum Province {

	BEIJING("0011", "北京", Area.BEIJING),
	TIANJING("0012", "天津", Area.TIANJING),
	HEBEI("0013", "河北", Area.SHIJIAZHUANG, Area.BAODING, Area.CANGZHOU, Area.CHENGDE, Area.HANDAN, Area.HENGSHUI, Area.LANGFANG, Area.QINHUANGDAO, Area.TANGSHAN, Area.XINGTAI, Area.ZHANGJIAKOU),
	SHANXI("0014", "山西", Area.TAIYUAN, Area.CHANGZHI, Area.DATONG, Area.JINCHENG, Area.LISHI, Area.LINFEN, Area.SHUOZHOU, Area.XINZHOU, Area.YANGQUAN, Area.YUCI, Area.YUNCHENG, Area.JINZHONG, Area.LVLIANG),
	NEIMENGGU("0015", "内蒙古", Area.HUHEHAOTE, Area.BAOTOU, Area.ALASHAN, Area.BAYANNAOER, Area.CHIFENG, Area.HULUNBEIER, Area.WUHAI, Area.WULANCHABU, Area.XILINGUOLE, Area.XINGAN, Area.EERDUOSI, Area.TONGLIAO),
	LIAONING("0021", "辽宁", Area.SHENYANG, Area.DALIAN, Area.ANSHAN, Area.BENXI, Area.CHAOYANG, Area.DANDONG, Area.FUSHUN, Area.FUXIN, Area.HULUDAO, Area.JINZHOU, Area.LIAOYANG, Area.PANJIN, Area.TIELING, Area.YINGKOU),
	JILIN("0022", "吉林", Area.CHANGCHUN, Area.BAICHENG, Area.BAISHAN, Area.JILIN, Area.LIAOYUAN, Area.SIPING, Area.SONGYUAN, Area.TONGHUA, Area.YANBIAN),
	HEILONGJIANG("0023", "黑龙江", Area.HAERBIN, Area.DAQING, Area.DAXINGANLIN, Area.HEGANG, Area.HEIHE, Area.JIXI, Area.JIAMUSI, Area.MUDANJIANG, Area.QITAIHE, Area.JIJIHAER, Area.SHUANGYASHAN, Area.SUIHUA, Area.YICHUN),
	SHANGHAI("0031", "上海", Area.SHANGHAI),
	JIANGSU("0032", "江苏", Area.NANJING, Area.CHANGZHOU, Area.HAIAN, Area.LIANYUNGANG, Area.NANTONG, Area.SUZHOU, Area.SUQIAN, Area.TAIZHOU, Area.WUXI, Area.XUZHOU, Area.YANCHENG, Area.YANGZHOU, Area.ZHENJIANG, Area.XUPU),
	ZHEJIANG("0033", "浙江", Area.HANGZHOU, Area.NINGBO, Area.HUZHOU, Area.JIAXING, Area.JINHUA, Area.SHAOXING, Area.TAI_ZHOU, Area.WENZHOU, Area.ZHOUSHAN, Area.QUZHOU, Area.LISHUI),
	ANHUI("0034", "安徽", Area.HEFEI, Area.ANQING, Area.BENGBU, Area.CHAOHU, Area.CHIZHOU, Area.CHUZHOU, Area.FUYANG, Area.HUAIBEI, Area.HUAINAN, Area.HUANGSHAN, Area.LUAN, Area.MAANSHAN, Area.TONGLING, Area.WUHU, Area.XUANCHENG, Area.BOZHOU, Area.SU_ZHOU),
	FUJIAN("0035", "福建", Area.FUZHOU, Area.XIAMEN, Area.LONGYAN, Area.NANPING, Area.NINGDE, Area.PUTIAN, Area.QUANZHOU, Area.SANMING, Area.ZHANGZHOU),
	JIANGXI("0036", "江西", Area.NANCHANG, Area.FU_ZHOU, Area.GANZHOU, Area.JIAN, Area.JINGDEZHEN, Area.JIUJIANG, Area.PINGXIANG, Area.SHANGRAO, Area.XINYU, Area.YI_CHUN, Area.YINGTAN),
	SHANDONG("0037", "山东", Area.JINAN, Area.QINGDAO, Area.BINZHOU, Area.DEZHOU, Area.DONGYING, Area.HEZE, Area.JINING, Area.LAIWU, Area.LIAOCHENG, Area.LINXI, Area.RIZHAO, Area.TAIAN, Area.WEIHAI, Area.WEIFANG, Area.YANTAI, Area.ZAOZHUANG, Area.ZIBO),
	HENAN("0041", "河南", Area.ZHENGZHOU, Area.ANYANG, Area.JIAOZUO, Area.HEBI, Area.KAIFENG, Area.LUOYANG, Area.NANYANG, Area.PINGDINGSHAN, Area.SANMENXIA, Area.SHANGQIU, Area.XINXIANG, Area.XINYANG, Area.XUCHANG, Area.ZHOUKOU, Area.ZHUMADIAN, Area.LUOHE, Area.FU_YANG, Area.JIYUAN),
	HUBEI("0042", "湖北", Area.WUHAN, Area.EZHOU, Area.ENSHI, Area.HUANGGANG, Area.HUANGSHI, Area.JINGMEN, Area.JINGZHOU, Area.SHIYAN, Area.SUIZHOU, Area.XIANNING, Area.XIANGFAN, Area.SHENNONGJIANG, Area.XIAOGAN, Area.TIANMEN, Area.YICHANG, Area.SANXIA),
	HUNAN("0043", "湖南", Area.CHANGSHA, Area.CHANGDE, Area.CHENZHOU, Area.HENGYANG, Area.HUAIHUA, Area.LOUDI, Area.SHAOYANG, Area.XIANGTAN, Area.XIANGXI, Area.YIYANG, Area.YONGZHOU, Area.YUEYANG, Area.ZHANGJAIJIE, Area.ZHUZHOU),
	GUANGDONG("0044", "广东", Area.GUANGZHOU, Area.SHENZHEN, Area.CHAOZHOU, Area.DONGGUAN, Area.FOSHAN, Area.HUIZHOU, Area.JIANGMEN, Area.JIEYANG, Area.MAOMING, Area.MEIZHOU, Area.QINGYUAN, Area.SHANTOU, Area.SHANWEI, Area.SHAOGUAN, Area.YANGJIANG, Area.YUNFO, Area.ZHANJIANG, Area.ZHAOQING, Area.ZHONGSHAN, Area.HEYUAN, Area.ZHUHAI),
	GUANGXI("0045", "广西", Area.NANNING, Area.BAISE, Area.BEIHAI, Area.GUILIN, Area.HECHI, Area.LIUZHOU, Area.WUZHOU, Area.YULIN, Area.CHONGZUO, Area.FANGCHENGGANG, Area.GUIGANG, Area.HEZHOU, Area.LAIBIN, Area.QINZHOU),
	HAINAN("0046", "海南", Area.HAIKOU, Area.SANYA, Area.BAISHA, Area.BAOTING, Area.CHANGJIANG, Area.CENGMAI, Area.ZHANZHOU, Area.DINGAN, Area.DONGFANG, Area.LEDONG, Area.LINGAO, Area.LINGSHUI, Area.QIONGHAI, Area.QIONGZHONG, Area.TUNCHANG, Area.WANNING, Area.WENCHANG, Area.WUZHISHAN, Area.YANGPU),
	CHONGQING("0050", "重庆", Area.CHONGQING),
	SICHUAN("0051", "四川", Area.CHENGDU, Area.BAZHONG, Area.DAZHOU, Area.DEYANG, Area.GUANGAN, Area.GUANGYUAN, Area.LESHAN, Area.LIANGSHAN, Area.MEISHAN, Area.MIANYANG, Area.NANCHONG, Area.NEIJIANG, Area.PANZHIHUA, Area.SUINING, Area.YAAN, Area.YIBIN, Area.ZIGONG, Area.LUZHOU, Area.ABA, Area.GANZI, Area.ZIYANG),
	GUIZHOU("0052", "贵州", Area.GUIYANG, Area.ANSHUN, Area.BIJIE, Area.LIUPANSHUI, Area.TONGREN, Area.ZUNYI, Area.QIANDONGNAN, Area.QIANNAN, Area.QIANXINAN),
	YUNNAN("0053", "云南", Area.KUNMING, Area.XISHUANGBANNA, Area.BAOSHAN, Area.CHUXIONG, Area.DALI, Area.DEHONG, Area.HONGHE, Area.LIJIANG, Area.LINCANG, Area.NUJIANG, Area.QUJING, Area.SIMAO, Area.WENSHAN, Area.YUXI, Area.ZHAOTONG, Area.ZHONGDIAN, Area.DIQINGZHOU),
	XIZANG("0054", "西藏", Area.LASA, Area.ALI, Area.CHANGDU, Area.LINZHI, Area.NAQU, Area.RIKAZE, Area.SHANNAN),
	SHAN_XI("0061", "陕西", Area.XIAN, Area.ANKANG, Area.BAOJI, Area.HANZHONG, Area.SHANGLUO, Area.TONGCHUAN, Area.WEINAN, Area.XIANYANG, Area.YANAN, Area.YU_LIN),
	GANSU("0062", "甘肃", Area.LANZHOU, Area.BAIYIN, Area.DINGXI, Area.DONGFENG, Area.HEZUO, Area.JIAYUGUAN, Area.JINCHANG, Area.JIUQUAN, Area.KUANGQU, Area.LINXIA, Area.LONGNAN, Area.PINGLIANG, Area.QINGYANG, Area.TIANSHUI, Area.WUWEI, Area.ZHANGYE, Area.GANNANZHOU),
	QINGHAI("0063", "青海", Area.XINING, Area.HAIDONG),
	NINGXIA("0064", "宁夏", Area.YINCHUAN, Area.ZHONGWEI, Area.GUYUAN, Area.SHIZHUISHAN, Area.WUZHONG),
	XINJIANG("0065", "新疆", Area.WULUMUQI, Area.AKESU, Area.ALETAI, Area.BAZHOU, Area.BO_ZHOU, Area.CHANGJI, Area.HAMI, Area.HETIAN, Area.KASHEN, Area.KELAMAYI, Area.MALAN, Area.SHIHEZI, Area.TACHENG, Area.TULUFAN, Area.YILI, Area.KEZHOU, Area.ALAER, Area.WUJIAQU),
	XIANGGANG("2001", "香港", Area.XIANGGANG),
	AOMEN("2002", "澳门", Area.AOMEN),
	TAIWAN("2003", "台湾", Area.TAIWAN);
	
	private Province(String code, String name, Area... areas) {
		this.code = code;
		this.name = name;
		this.areas = areas;
	}
	
	public String code;
	
	public String name;
	
	public Area[] areas;
	
	public static Province getProvByCode(String code) {
		for(Province province : Province.values()) {
			if(province.code.equals(code)) {
				return province;
			}
		}
		return null;
	}
	
	public static Area[] getAreasByCode(String code) {
		Province province = getProvByCode(code);
		if(province != null) {
			return province.areas;
		} else {
			return null;
		}
	}
 	
}